# Generated by Django 4.2 on 2024-12-11 21:15

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0006_friendship'),
    ]

    operations = [
        migrations.CreateModel(
            name='ServerCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=256, unique=True, verbose_name='Название')),
                ('description', models.TextField(blank=True, verbose_name='Описание')),
            ],
        ),
        migrations.CreateModel(
            name='Server',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=256, unique=True, verbose_name='Название')),
                ('description', models.TextField(blank=True, verbose_name='Описание')),
                ('photo', models.ImageField(upload_to='servers/', verbose_name='Аватарка')),
                ('is_private', models.BooleanField(default=False, verbose_name='Приватность')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='website.servercategory', verbose_name='Категория')),
            ],
        ),
        migrations.CreateModel(
            name='ServerMember',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('member', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Участник')),
                ('server', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='website.server', verbose_name='Сервер')),
            ],
            options={
                'unique_together': {('server', 'member')},
            },
        ),
    ]
