# Generated by Django 4.2 on 2024-12-11 22:11

from django.db import migrations
import fontawesome_5.fields


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0007_servercategory_server_servermember'),
    ]

    operations = [
        migrations.AddField(
            model_name='servercategory',
            name='icon',
            field=fontawesome_5.fields.IconField(blank=True, max_length=60, verbose_name='Иконка Font Awesome'),
        ),
    ]
