# Generated by Django 4.2 on 2024-12-13 17:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0009_alter_friendship_unique_together_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='message',
            old_name='file',
            new_name='uploaded_file',
        ),
    ]
