# Generated by Django 4.2 on 2024-12-13 18:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0011_alter_message_uploaded_file'),
    ]

    operations = [
        migrations.AlterField(
            model_name='message',
            name='uploaded_file',
            field=models.FileField(null=True, upload_to='chat_files'),
        ),
    ]
