# Generated by Django 5.1.4 on 2024-12-15 14:09

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0015_alter_message_message_serverpost'),
    ]

    operations = [
        migrations.AddField(
            model_name='serverpost',
            name='timestamp',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
