# Generated by Django 5.1.4 on 2024-12-15 15:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0016_serverpost_timestamp'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='serverpost',
            options={'ordering': ['-timestamp']},
        ),
        migrations.CreateModel(
            name='ServerRoom',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('server', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='website.server', verbose_name='Сервер')),
            ],
        ),
    ]
