# Generated by Django 6.0 on 2025-12-10 23:33

import website.storage
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0017_alter_serverpost_options_serverroom'),
    ]

    operations = [
        migrations.AddField(
            model_name='message',
            name='original_filename',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='message',
            name='message',
            field=models.TextField(null=True, verbose_name='Сообщение'),
        ),
        migrations.AlterField(
            model_name='message',
            name='uploaded_file',
            field=models.FileField(blank=True, null=True, storage=website.storage.PrivateMediaStorage(), upload_to='chat_files'),
        ),
        migrations.AddIndex(
            model_name='message',
            index=models.Index(fields=['sender', 'recipient', 'id'], name='website_mes_sender__546c33_idx'),
        ),
        migrations.AddIndex(
            model_name='message',
            index=models.Index(fields=['recipient', 'sender', 'id'], name='website_mes_recipie_77156a_idx'),
        ),
    ]
