# Generated by Django 4.2.27 on 2025-12-23 15:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0018_message_original_filename_alter_message_message_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='message',
            name='message',
            field=models.TextField(max_length=8192, null=True, verbose_name='Сообщение'),
        ),
        migrations.AlterField(
            model_name='server',
            name='description',
            field=models.TextField(blank=True, max_length=1024, verbose_name='Описание'),
        ),
        migrations.AlterField(
            model_name='servercategory',
            name='description',
            field=models.TextField(blank=True, max_length=256, verbose_name='Описание'),
        ),
        migrations.AlterField(
            model_name='servercategory',
            name='name',
            field=models.CharField(max_length=128, unique=True, verbose_name='Название'),
        ),
        migrations.AlterField(
            model_name='serverpost',
            name='post',
            field=models.TextField(max_length=1024, verbose_name='Пост'),
        ),
        migrations.AlterField(
            model_name='serverpost',
            name='title',
            field=models.CharField(max_length=256, verbose_name='Заголовок поста'),
        ),
    ]
