# Generated by Django 4.2.27 on 2026-01-26 11:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0019_alter_message_message_alter_server_description_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='customuser',
            options={'verbose_name': 'пользователя', 'verbose_name_plural': 'Пользователи'},
        ),
        migrations.AlterModelOptions(
            name='friendship',
            options={'verbose_name': 'заявку в друзья', 'verbose_name_plural': 'Заявки дружбы'},
        ),
        migrations.AlterModelOptions(
            name='message',
            options={'verbose_name': 'сообщение', 'verbose_name_plural': 'Сообщения'},
        ),
        migrations.AlterModelOptions(
            name='server',
            options={'verbose_name': 'сервер', 'verbose_name_plural': 'Сервера'},
        ),
        migrations.AlterModelOptions(
            name='servercategory',
            options={'verbose_name': 'категорию', 'verbose_name_plural': 'Категории серверов'},
        ),
        migrations.AlterModelOptions(
            name='servermember',
            options={'verbose_name': 'участника', 'verbose_name_plural': 'Участники серверов'},
        ),
        migrations.AlterModelOptions(
            name='serverpost',
            options={'ordering': ['-timestamp'], 'verbose_name': 'пост', 'verbose_name_plural': 'Посты серверов'},
        ),
        migrations.AlterModelOptions(
            name='serverroom',
            options={'verbose_name': 'комнату', 'verbose_name_plural': 'Комнаты серверов'},
        ),
    ]
