# Generated by Django 6.0.7 on 2026-07-17 18:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0020_alter_customuser_options_alter_friendship_options_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ZegoCloudConfiguration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('app_id', models.CharField(max_length=255, verbose_name='App ID')),
                ('server_secret', models.CharField(max_length=255, verbose_name='Server Secret')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'конфигурацию ZegoCloud',
                'verbose_name_plural': 'Конфигурации ZegoCloud',
                'ordering': ['-created_at'],
            },
        ),
    ]
