# Generated by Django 6.0.7 on 2026-10-08 22:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0021_zegocloudconfiguration'),
    ]

    operations = [
        migrations.AddField(
            model_name='message',
            name='client_message_id',
            field=models.UUIDField(blank=True, editable=False, null=True),
        ),
        migrations.AddConstraint(
            model_name='message',
            constraint=models.UniqueConstraint(condition=models.Q(('client_message_id__isnull', False)), fields=('sender', 'client_message_id'), name='uniq_message_sender_client_id'),
        ),
    ]
